### PR TITLE
Switch from headless browser to unofficial REST API

### LINKED ISSUE #2: Switching to direct API requests
Headless Chrome seems a bit overkill for a Node.js API wrapper, and may not work on all machines (see line 36 in chatgpt-api.ts). The ChatGPT API allows direct requests given a CSRF token (which doesn't seem to change in my testing) and a session token, which can be obtained through the `/api/auth/session` endpoint.

### PR DESCRIPTION
**Pull request by transitive-bullshit**
Fixes #2 

This PR switches from using a headless browser to automate the ChatGPT web UI to using it's underlying unofficial REST API.

This is a **major breaking change** and will result in a major version update.

cc @ElijahPepe @RomanHotsiy and @spaceworkplatform who have all helped w/ input & code to make this change.

### CODE REVIEW

**Review by ElijahPepe — APPROVED** [review]

File: src/chatgpt-api.ts [hunk 1]
```diff
@@ -16,6 +16,8 @@ export class ChatGPTAPI {
   protected _apiBaseUrl: string
   protected _backendApiBaseUrl: string
   protected _userAgent: string
+
+  // stores access tokens for up to 10 seconds before needing to refresh
   protected _accessTokenCache = new ExpiryMap<string, string>(10 * 1000)
```
Comment (ElijahPepe) [inline src/chatgpt-api.ts:21]: Is there a specific reason for a 10 second refresh? Could we potentially go longer?

Comment (transitive-bullshit) [reply src/chatgpt-api.ts:21]: Good call; yep, we could definitely go longer. I can make this configurable via the constructor.

I'm honestly not sure of a good default value. If you want to do some testing to figure out what the web UI is doing, that'd be really helpful.

**Comment by transitive-bullshit** [comment]
I'm just doing some testing on this, using it in production via the [twitter bot](https://github.com/transitive-bullshit/chatgpt-twitter-bot).

Everything is working well so far... but this is a major change, so I want to be sure before merging.
